version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: shop-app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dawid
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
